### ISSUE TITLE
bug in sstice_slice_and_remap overwritinng

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/HICCUP#8]
`hdc` is not defined and `sstice_slice_and_remap` fails if the output file already exists. To solve just need to delete the `hdc.` from this line:

https://github.com/E3SM-Project/HICCUP/blob/cc285884b3a9187c6687c6d0ebd78741ef36532d/hiccup/hiccup_data_class.py#L1511

**Comment by whannah1** [comment]
good catch, I'll implement this.
